set -g mouse on

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mode-keys vi
set -g status-keys vi

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind y setw synchronize-panes
